### ISSUE TITLE
Support for multi module project

### ISSUE THREAD

**Issue by ramasa** [dsyer/spring-boot-thin-launcher#12]
Works for single project but not on multi module project.
Is there any flag in gradle to package dependent projects instead of downloading in runtime 
>     compile project(':library')

Tried out in https://github.com/spring-guides/gs-multi-module/tree/master/complete and got the below error 
> java -jar gs-multi-module-application-0.0.1-SNAPSHOT.jar 
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	...
> Caused by: org.springframework.boot.cli.compiler.grape.DependencyResolutionFailedException: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact gs-multi-module:library:jar:unspecified: in central (http://repo1.maven.org/maven2/)

**Comment by dsyer** [comment]
You can do anything in Gradle `<wink/>`. Here's an example: https://github.com/dsyer/gs-multi-module/tree/feature/thin. If you use the normal Gradle convention of using the directory name for the artifactId, you can get rid of most of the additional configuration to do with the artifactId.

**Comment by ramasa** [comment]
I tried out https://github.com/dsyer/gs-multi-module/tree/feature/thin and still seeing the same error

> ~/Downloads/d2/gs-multi-module/complete/application/build/libs$ java -jar application-0.0.1-SNAPSHOT.jar 
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	...
> Caused by: java.lang.RuntimeException: Could not find artifact com.example:library:jar:0.0.1-SNAPSHOT in spring-snapshots (https://repo.spring.io/libs-snapshot)
> 	at org.springframework.boot.loader.thin.DependencyResolver.dependencies(DependencyResolver.java:180)

**Comment by dsyer** [comment]
What did you do exactly? You need to install the jars (i.e. `gradle build install`).

**Comment by ramasa** [comment]
After gradle build install its working in local.
But gives the below error when started in another machine

> Exception in thread "main" java.lang.reflect.InvocationTargetException        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)        at java.lang.reflect.Method.invoke(Unknown Source)        at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:92)        at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:77)Caused by: java.lang.IllegalArgumentException: File must exist        at org.springframework.boot.loader.data.RandomAccessDataFile.(RandomAccessDataFile.java:67)


Is there any option to package project(compile project ':library') dependency but download maven dependency during runtime

**Comment by dsyer** [comment]
> Is there any option to package project(compile project ':library') dependency but download maven dependency during runtime

No. You have to deploy all dependencies to a Maven repository, either remote or local to where the app runs (you can do that with Gradle).

Please open another issue (it's not really a gradle feature), and we can maybe do it after 1.0.0.
