### ISSUE TITLE
Command line options for debug/trace output specifically to log dependency resolution outcomes

### ISSUE THREAD

**Issue by olivergierke** [dsyer/spring-boot-thin-launcher#14]
I've just [added the thin launcher](https://github.com/olivergierke/spring-restbucks/commit/c2ce8ab862e2420f6f41a0b7ce218a60b66aca07) to Spring Restbucks and it generally works like a charm.

However, I tried to get some insight into what the launcher is doing but failed to get any output:

`java -Dthin.trace=true -jar target/restbucks-1.0.0.BUILD-SNAPSHOT.jar`

Do I miss anything? Might be worth mentioning that I use a pre-populated local Maven repository so there's no downloading expected. If that's the reason for the lack of output, it'd still be cool to see which dependencies the launcher is using from where.

**Comment by dsyer** [comment]
It's not `thin.trace` it's plain `trace` (that's what it says in the README). Hopefully that works (but you will get a lot of logs that way, not just "what came from where").

**Comment by fastnsilver** [comment]
Really nice work @dsyer! You considered and solved for quite a few more use cases than I had originally.  I will definitely recommend this packaging approach going forward.  Seems like it should be baked into Spring Boot Maven Plugin rather than as a separate dependency.  But I certainly understand why.

**Comment by dsyer** [comment]
Thanks @fastnsilver. Please leave general feedback on your original issue in Spring Boot: https://github.com/spring-projects/spring-boot/issues/1813.

**Comment by olivergierke** [comment]
Gotcha. I think I've been trapped by literally all other properties being namespaced to `thin.` and the samples using those. It looks like the `debug` and `trace` options leak into the app if used, i.e. I if I switch them on to see info about the launcher I also see debug or trace info for my app. So maybe flags scoped to the launcher only are worth adding?

**Comment by dsyer** [comment]
See also e338fd3 (in 1.0.3)

**Comment by olivergierke** [comment]
Thanks, Dave!
