### ISSUE TITLE
Support Spring Boot 2.0 with Gradle

### ISSUE THREAD

**Issue by wilkinsona** [dsyer/spring-boot-thin-launcher#30]
Spring Boot 2.0's Gradle plugin is fundamentally different to 1.x's and, as a result, the Thin Launcher doesn't work with Boot 2.0 (as of 2.0.0.M3). A couple of key differences:

1. `bootRepackage` no longer exists and `BootJar` tasks should be considered instead
2. Custom layouts are not (currently?) supported with Gradle in Boot 2.0

1 is relatively straightforward once we've figured out how Boot 2.0 support will be provided (alongside 1.x, in a 2.0 version of this plugin, something else?)

2 is trickier. I'm not yet convinced that supporting custom layouts in Gradle is the right thing to do, at least not in their current form. They make a lot of sense in Maven where things aren't as flexible, but in Gradle where `BootJar` inherits all the capabilities of Gradle's copy task there may be a more idiomatic and powerful way to do it. The downside would be that code sharing across build systems is lost.

**Comment by z0mb1ek** [comment]
cannot build it with Spring Boot RC1, any news?

**Comment by dsyer** [comment]
The "app" sample now uses Boot 2.0 (see commit 85f762). You need to `gradle build thinJar` explicitly still until we figure out a way to do that automatically.

**Comment by dsyer** [comment]
Should all be working now, at least for simple projects like the sample.
