### ISSUE TITLE
Add support for creating a fat-jar out of a thin-jar

### ISSUE THREAD

**Issue by thomasdarimont** [dsyer/spring-boot-thin-launcher#32]
In scenarios where one has access to an m2 repo or can upload co-located dependencies 
it is easy to use the thin jar approach. 

However in restricted environments a fatjar is more appropriate. In such cases it would be 
very convenient to be able to create a fatjar from a given thin jar. 

Perhaps something like this would do the trick:
```
java -jar thin.jar -Dthin.supersizeme=./fat.jar
```

**Comment by dsyer** [comment]
"supersizeme" v. funny

Good idea. Sort of a nuclear option for #15 (and easier to implement).

**Comment by dsyer** [comment]
Try this out:

```
    $ java -jar myapp.jar --thin.dryrun --thin.root=target/thin/root
    $ java -jar myapp.jar --thin.archive=maven://org.springframework.boot.experimental:spring-boot-thin-converter:1.0.7.BUILD-SNAPSHOT
    $ java -jar myapp-exec.jar
```

You can get a usage message by typing

```
$ java -jar myapp.jar --thin.archive=maven://org.springframework.boot.experimental:spring-boot-thin-converter:1.0.7.BUILD-SNAPSHOT
```

when there is no `target/thin/root` to grab the dependencies from.

I think this is an interesting route to provide additional tooling without needing to add more code (or more dependencies) to the `ThinJarLauncher`. Essentially you leapfrog from the thin launcher to a tool of your choice (the `thin.archive` only need to have a discoverable classpath and main class). The same mechanism could be used, for instance, to provide the features being asked for in #25.

**Comment by dsyer** [comment]
I think I understand, sort of. It looks like the function-controller wasn't running when I did the `kubectl delete`. The CLI reports success, but nothing actually happens, and apparently the controller can't cacth up to its own state when it comes back online.

When I deleted everything manually and tried again with the function-controller running the whole time it worked (all services and deployments called "uppercase" disappeared when they were deleted on the CLI).

**Comment by dsyer** [comment]
I changed it a bit in latest snapshots, so now it is `thin.library` (not `thin.archive`) that you need to set to transfer control to a tool. It's more consistent with the way the launcher is the "library" in the default case. E.g. the above is replaced by

```
$ java -jar myapp.jar --thin.dryrun --thin.root=target/thin/root
$ java -jar myapp.jar --thin.library=org.springframework.boot.experimental:spring-boot-thin-converter:1.0.7.BUILD-SNAPSHOT
$ java -jar myapp-exec.jar
```
(You don't need the `maven://` prefix for a library.)

One advantage of that is that the target jar can be specified with `thin.archive` if it is different than the main executable. E.g. this works

```
$ java -jar myapp.jar --thin.dryrun --thin.root=target/thin/root
$ java -jar myotherapp.jar --thin.archive=myapp.jar --thin.library=org.springframework.boot.experimental:spring-boot-thin-converter:1.0.7.BUILD-SNAPSHOT
$ java -jar myapp-exec.jar
```
