### ISSUE TITLE
Support for using Spring Boot without the parent POM

### ISSUE THREAD

**Issue by Punishme** [dsyer/spring-boot-thin-launcher#35]
When i'm using Maven's dependency management import (as described in https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-build-systems.html#using-boot-maven-without-a-parent), instead of including the parent POM spring-boot-starter-parent, the application launch fails with following error:

```
no main manifest attribute, in whatever.jar
```

MANIFEST.MF of a working thin jar, which is using the parent POM:

```
Manifest-Version: 1.0
Implementation-Title: whatever
Implementation-Version: 0.0.1-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: whoever
Implementation-Vendor-Id: com.example
Spring-Boot-Version: null
Implementation-Vendor: Pivotal Software, Inc.
Main-Class: org.springframework.boot.loader.wrapper.ThinJarWrapper
Start-Class: com.example.SpringBootApplication
Spring-Boot-Classes: 
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_141
Implementation-URL: http://projects.spring.io/spring-boot/whatever/
```

MANIFEST.MF of a broken thin jar, which is using the dependency management import:

```
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: whoever
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_141
```

**Comment by dsyer** [comment]
That's not just broken, it isn't even using the Spring Boot maven plugin. There are complete instructions for how to do that in the Spring Boot user guide (and in the maven plugin docs which are linked to there). Maybe if you post a complete sample someone can help you fix it.

**Comment by Punishme** [comment]
Okay, enclosed two sample applications:

1. One with a working thin packaging and a spring-boot-starter-parent POM:
[https://github.com/Punishme/spring-boot-thin-with-parent](https://github.com/Punishme/spring-boot-thin-with-parent)
2. One with a non-working thin packaging and a dependency management import:
[https://github.com/Punishme/spring-boot-thin-without-parent](https://github.com/Punishme/spring-boot-thin-without-parent)

The second one has an optional maven build profile, to get it running as a fat jar. Details are documented in the READMEs of the projects.

Did I configure something wrong in the project without parent POM or is this setting currently just not covered by the thin launcher?

**Comment by dsyer** [comment]
You forgot to put an execution in the plugin declaration. E.g.

```
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
```

**Comment by Punishme** [comment]
Jesus. I didn't took a look in the parent pom, to see that the repacking is a default setting, which must be set without the parent. Thanks for the eye-opener.
