### ISSUE TITLE
Cannot resolve dependency with version property

### ISSUE THREAD

**Issue by ascheman** [dsyer/spring-boot-thin-launcher#36]
I encounter the following error

```
[ERROR] 'build.plugins.plugin[org.springframework.boot:spring-boot-maven-plugin].dependencies.dependency.version' for org.springframework.boot.experimental:spring-boot-thin-layout:jar must be a valid version but is '${spring-boot-thin-maven-plugin.version}'. @ org.dukecon:dukecon-server-springboot:[unknown-version], URL [jar:file:/Users/ascheman/wrk/dukecon/dukecon_server/impl/target/dukecon-server-springboot-1.4-SNAPSHOT.jar!/META-INF/maven/org.dukecon/dukecon-server-springboot/pom.xml], line 669, column 22
```

The POM contains the following block (lines 660 - 671)

```
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.springframework.boot.experimental</groupId>
            <artifactId>spring-boot-thin-layout</artifactId>
            <!-- For some reason spring-boot-thin-maven-plugin or the embedded artifact resolver cannot use a version property here -->
            <!--<version>1.0.7.BUILD-SNAPSHOT</version>-->
            <version>${spring-boot-thin-maven-plugin.version}</version>
          </dependency>
        </dependencies>
```

As you can see from the comment everything is fine if I replace the version property with a real value.

**Comment by dsyer** [comment]
Well, you have to define the `spring-boot-thin-maven-plugin.version` property, if you are going to refer to it in your plugin config. Did you just forget to do that?

**Comment by dsyer** [comment]
Can you share a simple sample?

**Comment by ascheman** [comment]
You will find our project here: https://github.com/dukecon/dukecon_server (check out the develop branch). I have not yet pushed the branch with the thin launcher but can do that if necessary after some small clean up during the day. If you need a simpler example I can compile one based on your examples during the next days.

**Comment by dsyer** [comment]
Thanks for the link. A more minimal project that I can use to reproduce the issue would be better. No rush.

**Comment by dsyer** [comment]
I can't reproduce this problem without more detail. A simple parent child maven project works for me (https://github.com/scratches/thin-demo-parent).
