### ISSUE TITLE
Running jdeps on the jar

### ISSUE THREAD

**Issue by Hervian** [dsyer/spring-boot-thin-launcher#44]
I would like to run `jdeps` on my spring boot jar, but I assume that this must be run on the *fat jar*, and not on the thin jar.

Is there any option available, which will generate a fat jar, besides the thin jar? (In which case I could run `jdeps` on the fat, and deploy the thin.)

**Comment by dsyer** [comment]
Checkout the README: https://github.com/dsyer/spring-boot-thin-launcher#how-to-convert-a-thin-jar-to-a-fat-jar. I don't know if jdeps works on Spring Boot jars anyway though, does it? Wouldn't it be better to use the thin jar to construct a classpath for jdeps?

**Comment by Hervian** [comment]
Thank you for your comment. I hadn't noticed the useful "--thin.classpath" option.
And only now do I see your other useful notes on Java 9, Spring Boot and Jlink (https://github.com/dsyer/spring-boot-java-9). 

I will continue to manually list the needed modules in my batch script call to jlink then.

Best regards, Anders
