### ISSUE TITLE
Very large thin/root/repository

### ISSUE THREAD

**Issue by paterczm** [dsyer/spring-boot-thin-launcher#51]
Hello

Using this awesome thin launcher, I was able to split my 40 MB uberjar into a 100 kB thin jar and a 70 MB "thin" repository. Wondering were the additional 30 MB came from, I noticed that the launcher
* includes test scoped dependencies in the repository and
* spring-boot-thin-launcher-1.0.10.RELEASE-exec.jar is 10 MB fat.

Is there any way to reduce the repository size? This is a problem when iterating changes which affect the repository, because I end up updating an image layer that is larger than the original uber jar.

**Comment by dsyer** [comment]
There's nothing much we can do about the `spring-boot-thin-launcher`. No doubt there are unused classes in there, but your guess is as good as mine which ones. Feel free to experiment with the packaging, but I don't see any easy way to ensure you didn't miss something vital.

The test dependencies probably ought not to be downloaded. That's probably a useful new feature. Help welcome. You could work around it I suppose by using profiles to hide the test dependencies in the pom. Or by re-writing the pom that is packed into the jar.

Or better still, pre-compute the dependencies and store the result in a properties file (`java -jar ... --thin.classpath=properties`). I'm pretty sure the dependency graph isn't even calculated if you use the output as your `thin.properties`, so there's no way it's going to download anything else.

**Comment by dsyer** [comment]
Actually, you don't need the `spring-boot-thin-launcher` at runtime, if the classpath is precomputed as an actual command line argument. So you could compute it, save it in a build arg or something, and then throw the launcher away.

**Comment by paterczm** [comment]
Interesting ideas. Have you considered generating a fat jar instead of a thin/root/repository? That would not require a special launcher and would be easy to include on the classpath.

**Comment by dsyer** [comment]
That’s also an option (see the README). Generally startup time will be quicker for an exploded jar, but you can do it that way as well. The end result would be identical for practical purposes.

**Comment by paterczm** [comment]
I confirm I can exclude the 10 MB spring-boot-thin-launcher from the repository without breaking stuff. It also seems that DependencyResolver filters out non runtime dependencies, so even though they take space in the image unnecessarily, they are not actually loaded.

**Comment by dsyer** [comment]
Test and provided dependencies are now excluded before dependencies are resolved (instead of after). Should be more efficient.
