### ISSUE TITLE
Allow thin.root to be specified in plugin configuration

### ISSUE THREAD

**Issue by krraghavan** [dsyer/spring-boot-thin-launcher#52]
When we use the resolve goal of the thin plugin it would be nice to be able to specify the thin.root so that it doesn't always point to .  

The use case is this:
Suppose we have a number of microservices s1, s2, ... sn.
The libraries for this are placed in  a folder called (say) service-dependencies/thin/root/repository.
The maven build puts the dependencies for each service into this service-dependencies folder.  Essentially the microservices are part of a bigger system and our maven.repo.local has all other dependencies which I don't want to include with my microservice dependencies.  So we end up with a separate repo which contain just the microservice dependencies.

Allowing thin.root to be overridden will allow us to make the plugin write service dependencies to a diff repo.

**Comment by dsyer** [comment]
I’m not sure I understand. The `thin.root` does not relate to the repository location. Can you provide some concrete code that we can run and see the issue explicitly?

**Comment by krraghavan** [comment]
Here's my situation:

- Multi module maven build with about 90+ modules
- Multiple microservices each running as a spring cloud application
- Thin boot packaging used to package all the boot apps as a thin jar with all dependencies collected in a single location.  The entire thin app + dependencies are packaged into an RPM and installed on each VM instance of our cluster.  

The way I accomplish this is:

- microservices
    - pom.xml (Parent pom - contains my thin maven plugin)
    - s1
       - pom.xml <-- Each microservice does a dry run using the resolve goal to populate dependencies in the module microservices dependencies below (by using the outputDirectory attribute of the resolve goal)
       - src/
       - test
    - s2
       - pom.xml
       - src/
       - test
    .
    .
    .
    - sn
       - pom.xml
       - src/
       - test
- microservice-dependencies
   - build
      - thin
          - root
            - repository <--- All microservices put their dependencies here during the resolve goal execution

We also use (for various reasons that are project specific) on Jenkins a local maven repo which is specified with -Dmaven.repo.local.

When I run this on Jenkins this is the error I got

`13:28:29 Exception in thread "main" java.lang.IllegalStateException: Cannot locate library: ./repository/org/springframework/boot/experimental/spring-boot-thin-launcher/1.0.11.RELEASE/spring-boot-thin-launcher-1.0.11.RELEASE-exec.jar
13:28:29 at org.springframework.boot.loader.wrapper.ThinJarWrapper.launch(ThinJarWrapper.java:113)
13:28:29 at org.springframework.boot.loader.wrapper.ThinJarWrapper.main(ThinJarWrapper.java:90)`

Since the resolve goal assumes thin.root=. always, it was looking for the repository folder in the target folder of the microservice.  I got around this problem by making a soft link from repository in each target folder (in our cmake scripts) to the repository folder in the dependencies module.  If I understood correctly (and it's possible I didn't) if the thin.root were to be overrideable then I would be able to override thin.root to point to my dependencies folder and avoid needing to create this soft link.

Although this situation is peculiar to our build environment I thought that perhaps allowing thin.root to be overridden in the plugin would not be a totally project specific ask.  

Is my understanding incorrect?

**Comment by dsyer** [comment]
I think there's something missing. Either your understanding or mine.

The `thin.root` is hard coded to "." in the plugin because that's what it needs to be to meet the requirements of the "resolve" goal as documented - it copies the jar file to the output directory and runs it there, with `thin.root=.` to force the dependencies to be copied to that location.

Your error in Jenkins is maybe the thing we need to dig into. I think when you use `thin.root` that `maven.repo.local` is maybe used inconsistently by the `ThinJarWrapper` and the `ThinJarLauncher`. Possibly this has nothing to do with the specific layout of your projects, and everything to do with the fact that your CI build is different from your local one. Maybe you could reproduce the problem with a simple sample app like in the github repo for this project?

**Comment by krraghavan** [comment]
I think it's some combination of specifying **outputDirectory**, **thin.root** being . and **maven.repo.local** being used to cause this failure.  I worked around it by creating soft links in our cmake (our build env. uses cmake to invoke Maven along with compiling C++ code) to make the thin plugin happy.  I also ended up including the launcher as a dependency in my pom with exec classifier (I'm not sure if this is a requirement or not).  With these steps my plugin's resolve goal works.  I'll try and create an example to see if this is reproducible.  If the dependency is required probably worth documenting it.

**Comment by krraghavan** [comment]
On another note, I am using Spring boot 2.0.1 and started getting method not found errors.

`08:48:22.655 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.NoSuchMethodError: org.springframework.util.Assert.isTrue(ZLjava/util/function/Supplier;)V
	at org.springframework.boot.context.properties.bind.Bindable.withExistingValue(Bindable.java:162)
	at org.springframework.boot.context.properties.bind.Bindable.ofInstance(Bindable.java:192)
	at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.getFirstNonLoopbackHostInfo(HostInfoEnvironmentPostProcessor.java:48)
	at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.postProcessEnvironment(HostInfoEnvironmentPostProcessor.java:35)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.j`

I realized that it was because the launcher seems to depend on Spring 4.x.  Is there a plan to support 5.x Spring?  Is it safe to exclude these dependencies and include the Spring 5 ones.

**Comment by krraghavan** [comment]
ok - looks like its back to the drawing board for me.  I included the launcher as a dependency to get around my Jenkins woes but it includes an Assert class in the same package as the Spring core module with a diff signature (in 5.x) which causes this error.  So I can't do that it looks like.  Why are we redefining these util classes - at the very least can't we shade them by putting them in a diff package.

**Comment by dsyer** [comment]
I think that's a symptom of your having included the launcher as a dependency. Probably not a good idea. There are samples that use Boot 1.3, 1.4, 1.5 and 2.0, so I think you ought to be able to make it work.

**Comment by dsyer** [comment]
That change (401eee8) might fix your issue. Hard to say for sure without a solid set of steps to reproduce, but maybe you could try snapshots and see if it works for you (build is still in progress)?

**Comment by krraghavan** [comment]
Will do. Thx
Raghavan 

Please pardon my brevity and any typos as this mail is sent from my mobile device
