### ISSUE TITLE
thinProperties not downloading dependencies to thin.root / thinResolve

### ISSUE THREAD

**Issue by alessiostalla** [dsyer/spring-boot-thin-launcher#53]
Hello,

I'm writing an article on the Spring Boot Thin Launcher and thus I'm trying various configurations with Maven and Gradle. I've started from an existing Boot with Gradle project which I did not write myself, whose build.gradle is located at [https://github.com/eugenp/tutorials/blob/master/spring-boot-gradle/build.gradle](https://github.com/eugenp/tutorials/blob/master/spring-boot-gradle/build.gradle).

Compared to it, the file I'm working on only adds the thin launcher plugin and the Maven plugin.

If I run `gradlew thinResolve`, I get a `build/thin/root/repository` directory full of dependencies, as expected.

However, if I add the line:
`bootJar.dependsOn = [thinProperties]`
to the end of my `build.gradle`, `gradlew thinResolve` produces a `build/thin/root/repository` directory containing only the thin launcher itself and no other dependencies.

In either case, the thin jar works fine (the application starts). However, when it contains the thin.properties file, if I run the app with `java -jar build/libs/demo-0.0.1-SNAPSHOT.jar --thin.root=foo`, then the foo/repository directory again only contains the launcher, whereas if the jar is built without a thin.properties then the foo/repository is populated as I expect.

Is this a bug?

**Comment by dsyer** [comment]
Looks like a bug to me. When the `thin.properties` is there it thinks that there is nothing to do. You can work around it by running `thinResolve` before `build`, I guess.
