### ISSUE TITLE
Gradle build failing in shadow sample with Boot 2.0 and Gradle 4.8

### ISSUE THREAD

**Issue by dsyer** [dsyer/spring-boot-thin-launcher#55]
The changes that were made to support Boot 2.0 appear to be broken. What was supposed to happen:

1. For a simple one-jar project, the Spring Boot thick jar is omitted and instead a thin jar is built (like what happened in 1.5.x).
2. For a simple project when the user explicitly configures the Spring Boot thick jar, the result is a thick and a thin executable jar (this is what happens in the "app" sample).
3. For a project with the shadow plugin, and also applying the Spring Boot plugin, you get 2 jars, one is fat and flat (the shadow one) and the other is thin and executable (the boot one).

What actually happens: 1. and 2. work but 3. is broken (the "shadow" sample). Update the shadow sample to use Boot 2.0 and Gradle 4.8 to see it break:

```
diff --git a/samples/shadow/build.gradle b/samples/shadow/build.gradle
index 4b0f62c..b402e38 100644
--- a/samples/shadow/build.gradle
+++ b/samples/shadow/build.gradle
@@ -1,6 +1,6 @@
 buildscript {
        ext {
-               springBootVersion = '1.5.1.RELEASE'
+               springBootVersion = '2.0.3.RELEASE'
                wrapperVersion = '1.0.13.BUILD-SNAPSHOT'
         shadowVersion = '2.0.1'
        }
@@ -21,7 +21,8 @@ buildscript {
 apply plugin: 'java'
 apply plugin: 'maven'
 apply plugin: 'eclipse'
-apply plugin: 'spring-boot'
+apply plugin: 'io.spring.dependency-management'
+apply plugin: 'org.springframework.boot'
 apply plugin: 'com.github.johnrengelman.shadow'
 apply plugin: 'org.springframework.boot.experimental.thin-launcher'
 
@@ -30,7 +31,7 @@ version = '0.0.1-SNAPSHOT'
 sourceCompatibility = 1.8
 targetCompatibility = 1.8
 
-assemble.dependsOn = [shadowJar, bootRepackage]
+assemble.dependsOn = [shadowJar, bootJar]
 
 repositories {
        mavenLocal()
diff --git a/samples/shadow/gradle/wrapper/gradle-wrapper.properties b/samples/shadow/gradle/wrapper/gradle-wrapper.properties
index a0b2851..717f038 100644
--- a/samples/shadow/gradle/wrapper/gradle-wrapper.properties
+++ b/samples/shadow/gradle/wrapper/gradle-wrapper.properties
@@ -2,4 +2,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-3.4.1-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.8.1-bin.zip
```

The result is a "successful" build that does not contain a shaded jar:

```
$ (cd samples/shadow/; gradle clean build)
$ ls -l samples/shadow/build/libs/
total 96
-rw-rw-r-- 1 dsyer dsyer  2737 Jul  9 15:38 shadow-0.0.1-SNAPSHOT-all.jar
-rw-rw-r-- 1 dsyer dsyer 92625 Jul  9 15:38 shadow-0.0.1-SNAPSHOT.jar
```

The "all" jar is supposed to be a fat (flat) shaded jar, but it only contains the application classes. The other one is supposed to be an executable thin jar but actually it is a Boot "fat" jar without the `BOOT-INF/lib` - it is neither one thing nor the other.

The AWS sample in Spring Cloud Function is even more broken because it moans about the fact that a task called "thinJarShadowJar" does not exist. This can be fixed by simply removing the `afterEvaluate` that asserts its existence. I'll probably do that because it doesn't seem to help anyone.

**Comment by wilkinsona** [comment]
For 2., how do you propose to distinguish between the `bootJar` task that's created automatically when you apply the Boot plugin and a `bootJar` task that's been explicitly configured by the user? Do you mean a `BootJar` task that's named something other than `bootJar`?

3. seems like a rather weird setup. Why is the Boot plugin being applied at all? If you're using the Shadow plugin I'd expect the Shadow plugin to be applied and, ideally, for Boot's dependency management to be used. I wouldn't expect Boot's own plugin to be applied though.

**Comment by dsyer** [comment]
The shadow sample is in slightly better shape now. It actually builds 2 jars the right size and shape, but 
only one of them is executable.

> how do you propose to distinguish

I don't know. Do we need to distinguish? If the user configures a task called `bootJar` and isn't using the Boot plugin then that's a bit unexpected. Is that what you mean?

I think `BootJar` tasks called something other than `bootJar` was actually a feature we discussed once before, and isn't it actually supported in Boot 1.5 with the thin plugin, but with different names for everything?

> seems like a rather weird setup.

It isn't weird for the AWS sample mentioned above, for example. You have a Boot thin jar that can be used in a variety of scenarios (even as a library), and a shaded ueber jar that can be launched by AWS.

**Comment by wilkinsona** [comment]
> I don't know. Do we need to distinguish? 

Scenarios 1 and 2 suggested to me that distinguishing is necessary. One results in the thick jar being omitted while the other is both a thick jar and a thin jar. I was curious about the trigger for the different behaviours.

>  You have a Boot thin jar that can be used in a variety of scenarios (even as a library), and a shaded ueber jar that can be launched by AWS.

It's not that bit that I find a bit weird. It's using both Boot's plugin and the Shadow plugin to get there. I guess it's a side-effect of trying to support Boot 1.x and Boot 2.x with (largely) the same code, but it would be more Gradle-like if the thin plugin provided a custom jar task that built a thin jar without any reliance on Boot's normal Gradle plugin, particularly given that Boot's Gradle plugin doesn't support the custom layout stuff in 2.0 so it can't be adding much anyway.
