### ISSUE TITLE
README out of date.

### ISSUE THREAD

**Issue by jbellmann** [dsyer/spring-boot-thin-launcher#6]
Hi, this is a wonderful idea to keep the artefact as small as possible. Unfortunately the documentation in the README seems to be not up to date. The instructions on [how to configure Maven](https://github.com/dsyer/spring-boot-thin-launcher#maven) ends in a failed build. And it seems that [module-layout is not supported anymore](https://github.com/spring-projects/spring-boot/issues/8008)?
Furthermore a properties file 'thin.properties' is mentioned multiple times. But I cant find such a properties file generated in the jars build. Maybe this could be clarified?

**Comment by dsyer** [comment]
Thanks for the feedback. I think the README is clearer now. There are some more sample apps here: https://github.com/spring-cloud/spring-cloud-cli/tree/master/spring-cloud-launcher, and here: https://github.com/markfisher/spring-cloud-function if you want to crib from something that works.

**Comment by jbellmann** [comment]
Thanks, will have a look into it.
