### ISSUE TITLE
error log level too low and content wrong

### ISSUE THREAD

**Issue by rainmanhhh** [dsyer/spring-boot-thin-launcher#63]
in PomTask.java line 47-66:
```			
                         DependencyManagementExtension dependencies = getProject().getExtensions()
					.findByType(DependencyManagementExtension.class);
                         if (dependencies != null) {
				PomDependencyManagementConfigurer pomConfigurer = dependencies
						.getPomConfigurer();
				MavenPluginConvention maven = getProject().getConvention()
						.findPlugin(MavenPluginConvention.class);
				if (maven != null) {
					maven.pom().withXml(pomConfigurer)
							.writeTo(new File(output, "pom.xml"));
				}
				else {
					getLogger().info(
							"Skipping pom generation (maybe you forgot to apply plugin: 'io.spring.dependency-management'?)");
				}
			}
			else {
				getLogger().info(
						"Skipping pom generation (maybe you forgot to apply plugin: 'maven'?)");
			}
```
1. skip pom generation should be fatal error but not info(without pom, thinjar can't auto resolve the dependencies)
2. missing maven/dependency-management plugin log should be switched over

**Comment by dsyer** [comment]
I'm not sure it's an error if the user has provided a manual pom.xml (we could check). Happy to accept pull requests for changes in that direction.

Not sure what you mean by "switched over". Maybe a PR would be the best place to discuss it?

**Comment by rainmanhhh** [comment]
> I'm not sure it's an error if the user has provided a manual pom.xml (we could check). Happy to accept pull requests for changes in that direction.
> 
> Not sure what you mean by "switched over". Maybe a PR would be the best place to discuss it?

sorry my english is not so good. I will create a PR
