### ISSUE TITLE
Dependency Resolver: wrong default for snapshots enabled (false instead of true)

### ISSUE THREAD

**Issue by stefanocke** [dsyer/spring-boot-thin-launcher#67]
Hello,
the thin-launcher did not resolve my own snapshot dependencies.  
Debugging the thin-launcher yields:

- in org.springframework.boot.loader.thin.DependencyResolver.mavenRepositories(MavenSettings, DefaultRepositorySystemSession)  the default for snapshot enabled is **false**

See: 
https://github.com/dsyer/spring-boot-thin-launcher/blob/a6da361db954f178018f4e6c37144ec4114c44c7/launcher/src/main/java/org/springframework/boot/loader/thin/DependencyResolver.java#L332

- acording to https://maven.apache.org/ref/3.5.4/maven-settings/settings.html#class_snapshots it should be **true**

**Comment by dsyer** [comment]
That's interesting. I guess it's easy for you to work around. Send a PR?

**Comment by stefanocke** [comment]
Yes, the workaround is easy. Just enable snapshots explicitely in settings.xml:

```
<repository>
                    <id>...</id>
                    <url>...</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
</repository>
```
Will try to provide PR asap.

Thanks,
Stefan.

**Comment by stefanocke** [comment]
Same default (true) also for repositories in the POM:
https://maven.apache.org/ref/3.5.2/maven-model/apidocs/org/apache/maven/model/RepositoryPolicy.html#getEnabled--

> public String getEnabled()
>Get whether to use this repository for downloading this type of artifact. Note: While the type of this field is String for technical reasons, the semantic type is actually Boolean. Default value is true.

But as far as I understand, that should be the same line of code in DependencyResolver.

Fix is easy... Still looking for the right unit test.
