### ISSUE TITLE
DEFAULT_LIBRARY could be updated to M1?

### ISSUE THREAD

**Issue by jbellmann** [dsyer/spring-boot-thin-launcher#7]
As 'DEFAULT_LIBRARY' the ['ThinJarWrapper'](https://github.com/dsyer/spring-boot-thin-launcher/blob/master/wrapper/src/main/java/org/springframework/boot/loader/wrapper/ThinJarWrapper.java#L67) uses a '0.0.1.BUILD-SNAPSHOT'. Maybe this could/should be updated to the latest milestone?

**Comment by dsyer** [comment]
I think this is fixed (although it refers to a snapshot, not a milestone, in master, which seems logical to me).
