### ISSUE TITLE
Replace usage of jarjared Plexus code

### ISSUE THREAD

**Issue by wilkinsona** [dsyer/spring-boot-thin-launcher#71]
Via https://github.com/dsyer/spring-boot-thin-launcher/issues/70, I noticed that `ThinLauncherPlugin` is [using](https://github.com/dsyer/spring-boot-thin-launcher/blob/a6a93ac9e723aa1fb8f68b83a0bd13b0743c0642/gradle-plugin/src/main/java/org/springframework/boot/experimental/gradle/ThinLauncherPlugin.java#L26-L27) Plexus code that's been jarjared by the dependency management plugin. I consider that code to be an internal. It could be changed or removed at any time so it would make this plugin more robust if it didn't use it.

**Comment by dsyer** [comment]
It looks like generic utility stuff. I expect Gradle has tools for doing that kind of thing internally? Would you be able to suggest a sensible replacement?

**Comment by wilkinsona** [comment]
[java.nio.file.Files](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html) probably has what you need.

**Comment by dsyer** [comment]
Does that help with #70?

**Comment by wilkinsona** [comment]
I don't think so. Looking at [the source for `URLInputStreamFacade`](https://github.com/codehaus-plexus/plexus-utils/blob/e282b22a3ddbb2ea4ae4d4b429b3b93b89409584/src/main/java/org/codehaus/plexus/util/io/URLInputStreamFacade.java#L38), I suspect a `null` input stream would be passed into `Files.copy` in the same circumstances and it will NPE too.

**Comment by dsyer** [comment]
That's what I thought. I guess we need to find out why it was null (probably a bad jar file). Waiting for a response from OP.
