### ISSUE TITLE
spring-boot-thin:resolve does not work when ~/.m2/settings.xml does not use default local repository

### ISSUE THREAD

**Issue by dantran** [dsyer/spring-boot-thin-launcher#76]
see #75
it only populates spring-boot-thin wrapper

reproducible at https://github.com/dantran/myproj

**Comment by dsyer** [comment]
How do you mean "populate"? It seems to work for me (the "other" sample in this repo for example).

**Comment by dantran** [comment]
mvnrepo\pom.xml is used to populate  a maven repo to use with my demo app with thin.offline

it only shows  target\staging\repository\org\springframework\boot\experimental\spring-boot-thin-launcher\1.0.18.BUILD-SNAPSHOT\spring-boot-thin-launcher-1.0.18.BUILD-SNAPSHOT-exec.jar

**Comment by dsyer** [comment]
Is it anything to do with Windows then? Does it work without the offline flag (it's not specified in the pom I think)? I ran `mvn install` on your project and `target\staging\repository` was full of stuff.

**Comment by dantran** [comment]
with the latest finding, this issue is not windows related 

could you update your ~/.m2/settings.xml to use a different localRepository settings?

I am able to reproduce this issue on both windows and linux

**Comment by dsyer** [comment]
Please try a snapshot and check that it works. I think it works for me, but I'm not 100% sure I got your use case.

**Comment by dsyer** [comment]
Then obviously I don’t get your use case, because I tested the change I made and it works for me. Please explain a bit more or provide some steps to reproduce.
