### ISSUE TITLE
spring-boot-thin:properties process classifier dependency as primary dependency

### ISSUE THREAD

**Issue by dantran** [dsyer/spring-boot-thin-launcher#77]
my demo thin boot app and the following dependency

    <dependency>
      <groupId>com.mycomp.myproj</groupId>
      <artifactId>myproj-common</artifactId>
      <classifier>duplicate</classifier> 
    </dependency>

the generared entry of spring-boot-thin:properties goal has this 

    dependencies.myproj-common=com.mycomp.myproj\:myproj-common\:1.0-SNAPSHOT

No indication of the specified classifier which should be

   dependencies.myproj-common=com.mycomp.myproj\:myproj-common\:1.0-SNAPSHOT:duplicate

It also means thin boot picks up the wrong jar, in case of artifact without primary jar will crash at startup. We have packaging pom maven module with  a bunch of classifiers

To reproduce it   checkout https://github.com/dantran/myproj and view the generated 

    app-with-common-classifier/target/classes/META-INF/thin.properties

happens on both 1.0.17 ad 1.0.18-SNAPSHOT

**Comment by dantran** [comment]
Not sure how to reopen this, but your fix works for a single classifier, but I have scenarios where I need multiple classifiers coming from the same GAV.  

The thin key only cover  groupId.artifactid.version is not enough, thin boot needs to cover classifier at the key name as well

I updated my project have app-with-common-classifier to use 2 classifiers, the thin.properties only show one (  ie last one win)

**Comment by dsyer** [comment]
You can open a new issue I guess - please provide a sample to explain the details. I’m not sure really why you would need the same dependency with multiple classifiers. And if you do, you can certainly make it work if you write the properties file manually. Or did I miss something?
