### ISSUE TITLE
spring-boot-thin:properties filters out mutiltiple dependencies with the same artifactId

### ISSUE THREAD

**Issue by dantran** [dsyer/spring-boot-thin-launcher#80]
here is my dependency list

    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-client</artifactId>
    </dependency>
    <dependency>
      <groupId>com.sun.jersey</groupId>
      <artifactId>jersey-client</artifactId>
      <version>1.19.1</version>
    </dependency>

spring-boot-thin:properties  only shows this line ( last one wins)

    dependencies.jersey-client=com.sun.jersey\:jersey-client\:1.19.1

to produce it, checkout https://github.com/dantran/myproj and build

see app/target/classes/META-INF/thin.properties

likey the thin.properties   property name only account of artifactId and classifier, and miss out groupId to ensure uniqueness

**Comment by dsyer** [comment]
Sigh. I don’t know how much I really want to fix that. Two artifacts really shouldn’t have the same id. It would break in a WAR format as well.

**Comment by dsyer** [comment]
It would break in a WAR where the version was the same. This truly is pathological. If you want to find a solution and propose it via a PR, as long as it doesn't change the default behaviour when no such clash exists, go ahead and send a patch and I will probably be able to merge it. I can't make it a priority for such a corner case.

**Comment by dantran** [comment]
it is true, i would break for 2 GAV with same artifact id an version.  this is a very rare case.

The jersey-client situation is much more common

**Comment by dantran** [comment]
how about add changing format of key name to account for groupid

    dependencies.com.sun.jersey\:jersey-client=com.sun.jersey\:jersey-client\:1.19.1

?

**Comment by dsyer** [comment]
That would work, but I don’t think we should change the default to fix a pathological corner case. Also, a colon in a key name seems like a bad idea, so I would stick with periods.

**Comment by dantran** [comment]
my fix for spring-boot-thin:properties is not working yet. I forgot to account for the prefix 'dependencies' during comparison

Will submit another PR

**Comment by dantran** [comment]
@dsyer , I now have a full project with a number of spring-boot, spring app,  and vanilla cli converted to thin boot :-) running using the generated thin.properties at build time with thin.offline, thin.root and thin.repo pointing to same share local repo.    Thanks for the  support

**Comment by dsyer** [comment]
You are welcome. Thanks for the bug reports and patches.
