### ISSUE TITLE
Ability to support executable war

### ISSUE THREAD

**Issue by dongpanjiaolong** [dsyer/spring-boot-thin-launcher#84]

**Comment by dongpanjiaolong** [comment]
I deploy my war to remote tomcat, also take too long time.

**Comment by dsyer** [comment]
There's nothing we can really do about war files to make them smaller. The file format is part of the EE spec. If they were "thin" they wouldn't be deployable, even if they were executable. Unless I'm missing something, I don't think there is much we can do.
