### ISSUE TITLE
spring-thin-boot:properties Add option to use dependencies baseVersion 

### ISSUE THREAD

**Issue by dantran** [dsyer/spring-boot-thin-launcher#88]
My project has external snapshot dependencies and its intry show as 

    dependencies.vmware-util=groupId\:artifactId\:1.0.0-7-20181213.072101-4

Would like to see it as 

    dependencies.vmware-util=groupId\:artifactId\:1.0.0-7-SNAPSHOT

The solution would be to use artifact.getBaseVersion() instead when this option is enable

Do understand that with -SNAPSHOT, will look for latest at launch time. and that is behavior we would like to have.

Reasonable to ask? will provide a PR

**Comment by dsyer** [comment]
How did you specify this dependency in your pom (or build config)? Is it perhaps better to use dependency management?

**Comment by dsyer** [comment]
I’m not really sure what you are asking for then. Can you create a little sample?

**Comment by dantran** [comment]
here are the steps

  * Clone https://github.com/dantran/thinboot-demo.git
  * mvn clean install
  * view app/pom.xml and app/target/classes/META-INF/thin.properties

Would to see snapshot thin.properties shows as 

    dependencies.spring-boot-auto-reflect=org.springframework.boot.experimental\:spring-boot-auto-reflect\:1.0.0.BUILD-SNAPSHOT


instead of

    dependencies.spring-boot-auto-reflect=org.springframework.boot.experimental\:spring-boot-auto-reflect\:1.0.0.BUILD-20180724.103850-4

**Comment by dsyer** [comment]
Resolved in #89
