### ISSUE TITLE
runtimeOnly dependencies not included in maven pom.xml

### ISSUE THREAD

**Issue by MitchyGoodness** [dsyer/spring-boot-thin-launcher#93]
Had a Spring Cloud Task that connects to a postgres db. The spring initializr added the dependency for postgres support as "runtimeOnly('org.postgresql:postgresql')" within the gradle.build file.
The thin jar pom.xml was missing this necessary dependency and failed without it.

**Comment by dsyer** [comment]
Looks like a Gradle issue? If you use Gradle you need to configure it to generate a valid `pom.xml` (this is mentioned in the README). I'm not really a Gradle user so you probably have to figure that out for yourself. If you learn anything in the process please comment here.

**Comment by MitchyGoodness** [comment]
Sure. All I needed to do was switch runtimeOnly with runtime for it to get mapped. However this does expose a "hole" since runtime is deprecated in favor of runtimeOnly.

**Comment by dsyer** [comment]
I guess maybe that's a problem for the `maven` plugin in Gradle then?

**Comment by dsyer** [comment]
Might be working now with bbb1e80c.
