### ISSUE TITLE
settings.xml not being loaded from thin.root 

### ISSUE THREAD

**Issue by bondj** [dsyer/spring-boot-thin-launcher#99]
In the readme it says 
> This will download all the dependencies to ${thin.root}/repository, and look for Maven settings in ${thin.root}/settings.xml.

This does not appear to be working, as our local site-repository is only used when the settings.xml file is in ~/.m2.

I found that if I override user.root to point to the same directory as thin.root it works. (However, there are other libraries that rely on user.root property, so that's not a viable solution).

Looking at the code MavenSettingsReader.java is responsible for loading settings.xml but that is only constructed from non-test code passing in zero parameters, so user.home is always used outside test.

Is this an error in the documentation (ie it should never work), or an error in the implementation? Is there an easier way to specify our site-local repositories?

**Comment by dsyer** [comment]
Is it a problem to put `settings.xml` in `~/.m2`? It's actually quite likely that you'd want to re-locate the `repository` and not the `settings.xml` so we need to be careful about changing the default behaviour. Maybe add a new property for the location of `settings.xml`?

For the sake of clarity, it looks to me like the `MavenSettingsReader` always looks in `${user.home}/.m2/settings.xml`.

**Comment by dsyer** [comment]
Re-opening because of bizarre test failures. Not sure how to fix it yet because it doesn't seem related.

**Comment by dsyer** [comment]
Fixed the test. The default now is to use `settings.xml` from `${thin.root}/.m2` if it exists, and if not to fall back on `${user.home}/.m2`.
